spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect
  datasource:
    url: jdbc:mysql://mysql:3306/miniautorizador
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  error:
    include-stacktrace: never
