spring:
  jpa:
    hibernate:
      ddl-auto: update
      database: mysql
      dialect: org.hibernate.dialect.MySQL57Dialect
      connection:
        characterEncoding: utf-8
  datasource:
    url: jdbc:mysql://localhost:3306/miniautorizador
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  error:
    include-stacktrace: never
